### ISSUE TITLE
I tried to install the App in Switzerland and I got this error

### ISSUE THREAD

**Issue by zdavatz** [cocoa-mhlw/cocoa#13]
1. latest iOS version.
2. I tried to install the App in Switzerland and I got this error, see image below.
3. The error says "Network Connection Error."
4. My phone is fully connected.
![cocoa_error_jp](https://user-images.githubusercontent.com/4953/96855203-b0c24300-145c-11eb-93c1-dd6fa0eaf12c.png)

**Comment by zipperpull** [comment]
wontfix ラベルだけついていてラベルをつけた意図がわからないままなのですが、
現象としては「規約画面で同意ボタンを押したらネットワークエラーというアラートが表示された」という
ことかと思うのですが、発生条件や画面表示内容など含めて仕様通りということなのでしょうか？

仮に日本向けのアプリだから海外では動作しないのだとしても、ネットワークエラーという表示は
間違いではありませんか？

画面キャプチャの規約部分が日本語になっているのも気になりますがこれも仕様通りですか？
これは別問題なのかも？？

**Comment by keiji** [comment]
COCOAのサーバーは日本国外からのアクセスを遮断しているためIssueの動作は仕様通りとなります。エラーメッセージについては一般的なネットワークエラーと、今回のようにそもそもサーバーにアクセスできな状態をアプリとしてどのように判別するかという話になると思います。もしお知恵があれば別途Issueでご提案ください。

**Comment by cocoa-dev** [comment]
@zdavatz I apologize to your inconvenience. COCOA(server) doesn't accept connection from foreign countries.
If you are application developer, you can use Mock_Debug configuration. Thanks.

**Comment by zipperpull** [comment]
特にお知恵というわけではないのですが、海外から日本に入国する人は COCOA をインストールせよ、
という告知は出ていると思うので、適切なアナウンスがなされていることを期待します
(が以下のページにはみあたらなさそうですが)

外務省: https://www.mofa.go.jp/ca/cp/page22e_000925.html
PlayStore (英語版) : https://play.google.com/store/apps/details?id=jp.go.mhlw.covid19radar&hl=en

**Comment by Miki808** [comment]
iPhoneXs MaxでCOCOAを　ここ、ハワイでインストール中、　Network connection error  Please check your network connection  と出てきます。上記のスイスの件と同じ事象です。全てWi-Fiはつながっているのに、Terms of Useの同意をするとこまできて、止まっている状態です。去年、日本に行く前にこれはインストールできたような覚えがあるのですが、これは海外ではインストールできないのでしょうか？日本に着いてからインストールしてもいいのか、または、携帯自体が悪いのか、心配です。

I'm getting the message, Network connection error - Plz check your netowrk. when trying to click 'I accept the terms of use'. All apps work fine with my iPhone on my home wifi.  Is COCA installable outside Japan?

**Comment by keiji** [comment]
@Miki808 
If you are using iPhoneXs installed iOS 13.7+. it's not your(your phone's) fault. COCOA can be installed but cannot be activated from outside Japan. 
You can activate COCOA at the place you arrived(e.g. Airport).

And now, we are considering that remove this restrict. Because we confirmed another case, the network connection provided by roaming(e.g. Google Fi) always be connected from within the US.

iPhoneXs Maxをお使いで、iOS 13.7以上であれば、お使いの携帯に問題ないと考えます。
COCOAは、日本以外の国からインストールできますが、アクティベート（利用開始）はできません。日本国内に着いてから空港などで利用開始をお願いします。

**Comment by keiji** [comment]
@Miki808
Today, COCOA can be activated from outside Japan.
Thank you.
